config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {session: 'session', registration: 'registration'}
  get 'home/index'
  get 'home/confidential'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
	resources :shop do
  	resources :operating_hours
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	has_and_belongs_to_many :shops
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true
	validates :image_url, presence: true

end

app/models/operating_hour.rb
class OperatingHour < ApplicationRecord
	belongs_to :shop
	validates_presence_of :day, :shop_id
	validates_inclusion_of :day, :in => 0..6
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user, optional: true
	has_and_belongs_to_many :items
	has_many :operating_hours, dependent: :destroy
	geocoded_by :adress
  after_validation :geocode
	has_one_attached :frontpicture
  has_many_attached :pictures
	validates :title, presence: true
	validates :adress, presence: true

	def open?
		@time = Time.now.to_formatted_s(:time)
		if Time.now.strftime('%H:%M') > '00:00' and Time.now.strftime('%H:%M') < '07:00'
			day = Time.now.advance(days: -1)
		else
			day = Time.now
		end
		day = day.strftime("%w")
		@open = self.operating_hours.find_by(day: day)
		@open_time = @open[:open].to_formatted_s(:time)
		@close_time = @open[:close].to_formatted_s(:time)
		
		if @open_time < @close_time
			if @time >= @open_time && @time <= @close_time
				return true
			else
				return false
			end
		else
			if @time <= @open_time && @time >= @close_time
					return false
				else
					return true
				end
			end
	end
	def close_soon?
		if self.open?
			if Time.now + 60*30 >= @close_time
				return true
			else
				return false
			end
		end
	end
end

app/models/shops_item.rb
class ShopsItem < ApplicationRecord
	belongs_to :shop
	belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password,:password_confirmation)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@shops = Shop.all
    @shop = Shop.first
  end
  def confidential
  end
end

app/controllers/operating_hours_controller.rb
class OperatingHoursController < ApplicationController
	before_action :shop_all_hours, only: [:index, :create, :edit, :update]	
	before_action :shop_day_hours, only: [:edit, :update]
	respond_to :html, :js

	def show
	end

	def edit
	end
	
	def update
		id_shop= params[:shop_id]
 		@hour.update_attributes(hours_params)
	
	end

private
	def shop_all_hours
		@shop = Shop.find(params[:shop_id])
		@hours = @shop.operating_hours
	end
	def shop_day_hours
		@hour = @shop.operating_hours.find(params[:id])
	end	
  def hours_params
    params.require(:operating_hour).permit(:open, :close)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
	before_action :all_shops, only: [:index, :create]
	before_action :shop, except: [:new, :create, :index]
	after_action :create_operating_hours, only: [:create], if: -> {@shop.save}
	respond_to :html, :js
	
		def new
			@shop = Shop.new
		end
		def create
			@shop = Shop.new(shop_params)
			if @shop.save
				redirect_to shop_path(@shop.id)
			else
				render :action => 'new'
			end
		end
	
  def show
	  @hours = @shop.operating_hours
	end
	def edit
	end
  def update
		if params[:commit] == "Upload"
		  @shop.frontpicture.attach(params[:shop][:frontpicture])
    	redirect_to "/shop/#{params[:id]}"
			
		else
			 	if  @shop.update_attributes(shop_params)
    		redirect_to "/shop/#{params[:id]}"
    		else
      	render :action => :edit
    	end
 	 end
end
	def destroy
    @shop.destroy
    redirect_to "/shop"
  end
	private
	def shop
    @shop = Shop.find(params[:id])
	end
	def all_shops
		@shops = Shop.all
	end

	def shop_params
		params.require(:shop).permit(:title, :adress, :tobacco, :user_id)
	end

	def create_operating_hours
    @shop.operating_hours.create(name_of_day: 'Dimanche' ,day: 0, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Lundi' ,day: 1, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Mardi' ,day: 2, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Mercredi' ,day: 3, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Jeudi' ,day: 4, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Vendredi' ,day: 5, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
		@shop.operating_hours.create(name_of_day: 'Samedi',day: 6, open: '10:00', close: '02:00',valid_from: '01/10/2018', valid_through: '31/12/2018')
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
			
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operating_hours_helper.rb
module OperatingHoursHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/about.html.erb
<div class="dashboard-main">
  <div class="container">
  	<h1>L'ÉQUIPE ALIM-ALÔ</h1>
		<div class="members">
	        <%= image_tag("STEPHANE.png", class:"member-1") %>
	        <%= image_tag("AXEL.JPG", class:"member-2") %>
	        <%= image_tag("VICTORIAN.JPG", class:"member-3") %>
	        <%= image_tag("AMBROISE.JPG", class:"member-4") %>
	        <%= image_tag("KARL.JPG", class:"member-5") %>
      	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alimalo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDj0Fc9HAMlqJi5YeIkrGkVLPp2GOm_8r8" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name='turbolinks-visit-control' content='reload'>

  </head>

  <body>
    
    <%= render "shared/navbar" %>
    <%= render "shared/alert" %>    
    <% unless user_signed_in? %>
      <%= render partial: 'devise/registrations/new' %>
      <%= render partial: 'devise/sessions/new' %>
    <% end %>

    <%= yield %>

    <%= javascript_include_tag 'application'%>

  </body>
</html>

app/views/operating_hours/_form.html.erb
<br>
<% if current_user %>
	<% if current_user.id == @shop.user_id %>
		<%= form_for @hour, url: {action: "update"}, html: {class: "nifty_form"}, remote: true do |f| %>

		<div class="form-row">

		<div class="col">
  			<%= f.time_field :open, class:"form-control"%>
		</div>

  		<div class="col">
  			<%= f.time_field :close, class:"form-control"%>
		</div>

		<div class="col">
		<%= f.submit "Mettre à jour", class:"btn btn-outline-dark" %>
		</div>
	</div>	
		<%end%>
	<% end %>
<% end %>

app/views/operating_hours/_hours.html.erb
<%@hours = @hours.sort_by { |h| h[:day]} %>
<% @hours.each do |h| %>
<li>
	<%if h[:open] == nil %>
		<p><em>fermée le <%=h[:name_of_day]%></em></p>
	<%else%>
		<b><%=h[:name_of_day]%></b>
		<% string = h[:open].to_s %>
		, Ouverture:<%= string[10..15] %>
		<% string = h[:close].to_s %>
		, Fermeture:<%= string[10..15] %>
	<%end%>
<span class="edit">
	<%=link_to " MODIFIEZ", edit_shop_operating_hour_path(@shop.id,h.id), remote: true%></span>
</li>
<%end%>

app/views/operating_hours/edit.js.erb
$('#hour-form').html("<%= j (render 'form') %>");
$('#hour-form').slideDown(350);

app/views/operating_hours/index.html.erb
  <% if current_user %>
		<% if current_user.id == @shop.user_id %> 
	<div class="container">
  	<div class="jumbotron" style="margin-top: 50px">

  		<h3>Faites savoir vos horaires en temps réel !</h3>
  		<p>Les utilisateurs pourront venir sans inquiétudes</p>

		<div id="hour-form"></div><br>
	
		<div id="hours">
		<%=render 'hours'%>
  </div>
</div>
		<%else%>
		<p> Cette espace est reservée au propriétaire</p>
	<% end %>
	<%else %>
	<p> Vous n'êtes pas connecté</p>
<% end %>

app/views/operating_hours/update.js.erb
$('#hours').html("<%= j (render 'hours') %>");
$('#hour-form').slideUp(350);

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/index.html.erb
<h1>Places#index</h1>
<p>Find me in app/views/places/index.html.erb</p>

app/views/places/new.html.erb
<h1>Places#new</h1>
<p>Find me in app/views/places/new.html.erb</p>

app/views/shared/_alert.html.erb
<p class="notice" style="position: absolute"><%= notice %></p>
<p class="alert alert-light" style="opacity: 0.4"><%= alert %></p>

app/views/shared/_cookie.html.erb
<div id="cookieConsent">
    <div id="closeCookieConsent">x</div>
    <div class="message">En poursuivant votre navigation sur ce site, vous acceptez nos Conditions Générales d'Utilisation et l'utilisation de cookies. Pour en savoir plus... <a href="/home/confidential">voir notre politique de confidentialité.</a><a class="cookieConsentOK">J'accepte</a></div>
</div>

<script >
	
	$(document).ready(function(){   
    setTimeout(function () {
        $("#cookieConsent").fadeIn(200);
     }, 4000);
    $("#closeCookieConsent, .cookieConsentOK").click(function() {
        $("#cookieConsent").fadeOut(200);
    }); 
}); 
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-default container-fluid pl-6">
  <div id="alimlogo">
    <%= link_to(image_tag('alim-alo.png', class:"navbar-brand"), root_path) %>
  </div>

  <div class="defileParent">      
    <p class="defile" data-text=" ne manque plus de rien le soir // ne manque plus de rien le soir //ne manque plus de rien le soir // ne manque plus de rien le soir // ne manque plus de rien le soir // ne manque plus de rien le soir //ne manque plus de rien le soir // ne manque plus de rien le soir //"> ne manque plus de rien le soir //</p>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>
        ALIMENTATION GENERALE</b></a>
        <div class="dropdown-menu" aria-labelledby="navbarNavDropdown">
          <a class="dropdown-item" href="/shop">LES ALIMS</a>
          <!-- <a class="dropdown-item" href="/">MAGAZINE ALIM</a>
          <a class="dropdown-item" href="/">RADIO ALIM</a> -->
          <a class="dropdown-item" href="home/about">À PROPOS D'ALIM-ALO</a>
        </div>

      <%if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>VOTRE ESPACE</b></a>
          <div class="dropdown-menu" aria-labelledby="navbarNavDropdown" id="espacepro">
						<% if shop_id = Shop.find_by(user_id: current_user.id) %>
						  <a data-toggle="modal" data-target="#signUpModal"><%= link_to "VOTRE BUREAU", shop_path(shop_id), class:"dropdown-item"%></a>
             <% else %>
							<a data-toggle="modal" data-target="#signUpModal"><%= link_to "VOTRE BUREAU", new_shop_path, { :user_id => current_user.id, class:"dropdown-item" } %></a>
							<%end%>
              <a data-toggle="modal" data-target="#logInModal"><%=  link_to "DECONNEXION", destroy_user_session_path, method: :delete, class:"dropdown-item" %></a>
              <a class="dropdown-item" href="/home/confidential">CGU</a>
            </div>

        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><b>ESPACE PRO</b></a>
            <div class="dropdown-menu" aria-labelledby="navbarNavDropdown" id="espacepro">
              <a class="dropdown-item" data-toggle="modal" data-target="#signUpModal">REJOINDRE</a>
              <a class="dropdown-item" data-toggle="modal" data-target="#logInModal">CONNEXION</a>
              <a class="dropdown-item" href="/home/confidential">CGU</a>
            </div>
          </li>
        <% end %>
      </li>
    </ul>
  </div>

</nav>

app/views/shared/_pulse.html.erb
<span class="pulse"></span>

app/views/shop/edit.html.erb
<% if current_user.id == @shop[:user_id] %>
<div class="container" id="newshop">
	<div class="jumbotron">

		<%= simple_form_for @shop , url: {action: "update"} do |f|   %>
			<%= f.input  :title, label: "Nom de l épicerie", error: "Nom de l'épicerie requis s'il vous plait" %>
		 	<%= f.input :adress, placeholder: 'Exemple: 5 Rue Francois Mitterrand, Paris', error: "Entrez votre adress suivant le même format que ci-dessus" %>
			<%= f.input :tobacco, label:'Papier à rouler / Préservatifs' %>
			<p><%= f.hidden_field :user_id, :value => current_user.id %></p>
		<%= f.button :submit%>
		<% end %>
	</div>
</div>
<%else%>
<p> Vous n' êtes pas le proprietaire de cette epicerie </p>
<% end %>

app/views/shop/index.html.erb
<div class="container">
  <br>
	<div id="shop-form"><div>
		<div id="sucess"></div>
</div>
  <div class="jumbotron">
		<h2>LES ALIMENTATIONS GÉNÉRALES PRÈS DE CHEZ VOUS</h2>
		 	<div class="list-alim">   
         <% @shops.each do |shop|%>
          <ul class="list-unstyled">
            <li class="product">
              <div id="picture" alt="">

              <div class="product-description">
                <h3><%= shop.title%></h3>
                <p><%= shop.adress%></p>
      					<%= link_to "SHOW", shop_path(shop.id) %>
              </div>
            </li>
          </ul>
         <%end%> 
      </div>

      <!-- BUTTON TO OPEN A NEW SHOP-->
    <% if current_user %>
  <%= link_to new_shop_path ,{ :user_id => current_user.id}, :method => :get do %>
        <button class="btn btn-dark float-right">PLACER NOUVELLE ALIMENTATION GÉNÉRALE</button>
      <% end %>
    <% end %>

  </div>
</div>

app/views/shop/new.html.erb
<% if current_user %>
<div class="container" id="newshop">
	<div class="jumbotron">
		<%=simple_form_for @shop , url: {action: "create"} do |f|   %>
	  	<%= f.input  :title, label: "Nom de l épicerie", error: "Nom de l'épicerie requis s'il vous plait" %>
	  	<%= f.input :adress, placeholder: 'Exemple: 5 Rue Francois Mitterrand, Paris', error: "Entrez votre adress suivant le même format que ci-dessus" %>
		<%= f.input :siret, placeholder: '123 568 94', error: " Numero de Siret requis" %>
		<%= f.input :tobacco, label:'Papier à rouler / Préservatifs' %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.button :submit%>
	<% end %>
	</div>
	<% else %>
	<p> Authentifcation requise, connectez vous </p>
	<%end%>
</div>

app/views/shop/show.html.erb
	<div class="dashboard-main">
	  <div class="container">
		<% if current_user %>
			<% if current_user.id == @shop[:user_id]%>
		<h1>Bonjour <%= current_user.username%>, bienvenue sur votre bureau! </h1>
		<h3>Ici, vous pouvez gérer votre profil en temps réél.</h3>
		<% end%>
		<% else%>
		<h1> Bonjour, voici l'épicerie <h1>
		<h3>Ici, vous pouvez  consulter les horaires en temps réél.</h3>
	<%end%>

		<div class="dashboard">
			<div class="row">
			<div class="dashboard-left col-6">
				<h2><%= @shop.title%></h2>
				<h4><%= @shop.adress%></h4>
				<% if @shop.frontpicture.attached? %>
					<%= image_tag @shop.frontpicture, class:"dashboard-image" %>
				<% end %><br>
				<br>
		<% if current_user %>
			<% if current_user.id == @shop[:user_id] %>
				<h6>Modifiez votre image ci-dessous</h6>
				<%= form_for @shop, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
				<%= f.file_field :frontpicture, class:"btn btn-outline-dark" %>
				<%= f.submit "Upload", class:"btn btn-outline-dark" %>
				<% end %>
			<% end %>	
				
			<%end %>
			<br>
		<% if current_user %>
				<% if current_user.id == @shop[:user_id] %>
					<%= link_to "Modifiez", edit_shop_path(@shop.id),class:"btn btn-outline-dark" %>
					<%= link_to "Suprimer l'épicerie" , @shop, :method => 'delete', data: { confirm: "Êtes-vous sur de vouloir fermer votre épicerie ? Elle disparaitra de la carte !" }, class:"btn btn-outline-dark" %>
				<%end %>
			<% end %>

			</div>

			<div class="dashboard-right jumbotron col-6 col-md-6 col-md-offset-1">
				<br><br>
				<% @hours = @hours.sort_by {|h| h[:day]}%>
				<% @hours.map do |h| %><br>
					<%if h[:open] == nil %>
						<p><em>fermée le <%=h[:name_of_day]%></em></p>
					<%else%>
						<%=h[:name_of_day]%>
						<% string = h[:open].to_s %>
						Horaires d'ouverture:<%= string[10..15] %>
						<% string = h[:close].to_s %>
						Horaire de fermeture:<%= string[10..15] %>
					<%end%>
				<%end%><br><br><br>

		<% if current_user %>
			<% if current_user.id == @shop[:user_id]%>
				 
				<p><em>Si vous êtes l'épicier:</em> </p>
				<h6><%= link_to "Modifier les horaires", shop_operating_hours_path(params[:id]), class:"btn btn-outline-dark" %> </h6>
			<%end%>
			<%end%>
			</div>

		</div>
		</div>
	  </div>
	</div>